---
- hosts: "{{ passed_in_hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes

    - name: install dependencies
      yum:
        name: "{{ packages }} "
        state: present
      vars:
        packages:
        - git
        - amazon-linux-extras
        - python3-pip

    - name: install docker
      shell: "amazon-linux-extras install docker -y"

    - name: Enable Docker service at startup
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        append: yes
        groups: docker

    - block:
      - name: clone repo
        git:
          repo: https://github.com/IgorMishchuk/weissbeerger-docker.git
          dest: ./weissbeerger-docker
      
      # - name: Ensure docker-compose is installed
      #   shell: pip3 install docker-compose --user
      - name: Ensure docker-compose is installed and available
        get_url: 
          url : https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)
          dest: /usr/local/bin/docker-compose
          mode: 'u+x,g+x'

      - name: Build and start containers
        shell: docker-compose up -d
        args:
          chdir: weissbeerger-docker/
          executable: /bin/bash

      - name: Wait until Jenkins is up
        shell: result_first=1; while [[ $result_first != 0 ]]; do if [[ `docker logs jenkins | grep 'Jenkins is fully up and running'` ]];then result_first=0;else sleep 4;fi;done
        register: result
        until: result.rc == 0
      become_user: ec2-user